import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-teal-500 text-4xl p-4 flex justify-center items-center">
          <Link className="m-3" href="/">
            Home
          </Link>
          <Link className="m-3" href="./Posts">
            Posts Page
          </Link>
          <Link className="m-3" href="./articles">
            Articles Page
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
